{{ if $.Values.IngressRouteDomain -}}

---

apiVersion: "traefik.io/v1alpha1"
kind: "Middleware"

metadata:
  name: "ssh-to-prom-basicauth"
  namespace: "{{ $.Release.Namespace }}"

spec:
  basicAuth:
    secret: "ssh-to-prom-basicauth"


---

apiVersion: "traefik.io/v1alpha1"
kind: "IngressRoute"

metadata:
  name: "ssh-to-prom"
  namespace: "{{ $.Release.Namespace }}"

spec:

  entryPoints:
    - "websecure"

  routes:
    - kind: "Rule"
      match: "Host(`{{ $.Values.IngressRouteDomain }}`)"
      services:
        - name: "ssh-to-prom"
          port: 80
      middlewares:
        - name: "ssh-to-prom-basicauth"


{{ end }}

