apiVersion: "v1"
kind: "Secret"
type: "Opaque"

metadata:
  name: "{{ $.Release.Name }}-basic-auth-secret"
  namespace: "{{ $.Release.Namespace }}"

data:

  auth: {{ htpasswd $.Values.IngressBasicAuthUsername $.Values.IngressBasicAuthPassword | b64enc }}

