---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Namespace }}-basic-auth-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd $.Values.IngressBasicAuthUsername $.Values.IngressBasicAuthPassword | b64enc }}

