apiVersion: "v1"
kind: "Secret"
type: "Opaque"

metadata:
  name: "ssh-to-prom-basicauth"
  namespace: "{{ $.Release.Namespace }}"

stringData:
  auth: |
    {{ htpasswd $.Values.IngressBasicAuthUsername $.Values.IngressBasicAuthPassword }}
  users: |
    {{ htpasswd $.Values.IngressBasicAuthUsername $.Values.IngressBasicAuthPassword }}

