---

ImageNameGithubSshToProm: "ghcr.io/shoce/ssh-to-prom"
ImageTagGithubSshToProm: ""

IngressDomain: "ssh-to-prom.domain.com"
IngressBasicAuthUsername: ""
IngressBasicAuthPassword: ""


AuthLogPath: "/var/log/auth.log"

MetricsPort: 80

DEBUG: false


IngressRequestMaxBodySizeString: "200m"

IngressWhitelistSourceRange:
- 127.0.0.0/8
- 10.0.0.0/8
- 172.16.0.0/12
- ::1/128
- fe80::/10


